name: Deploy App

on:
  push:
    paths:
      - "app/**"
      - ".github/workflows/app-deploy.yml"

jobs:
  deploy-app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Login to GHCR
      - name: Login to GHCR
        run: |
          echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u vateam0864-glitch --password-stdin

      # Build App Image
      - name: Build app image
        run: |
          docker build -t lnpr-app:latest ./app
          docker tag lnpr-app:latest ghcr.io/vateam0864-glitch/lnpr-cicd-template:latest

      # Push Image
      - name: Push image to GHCR
        run: docker push ghcr.io/vateam0864-glitch/lnpr-cicd-template:latest

      # Step: Select server(s)
      - name: Select Target Servers
        id: server_select
        run: |
          HOSTS="${{ secrets.EC2_HOST }}"
          TARGET="${{ secrets.TARGET_SERVER }}"

          if [ "$TARGET" = "all" ]; then
            SELECTED="$HOSTS"
          elif [ "$TARGET" = "server1" ]; then
            SELECTED=$(echo "$HOSTS" | cut -d',' -f1)
          elif [ "$TARGET" = "server2" ]; then
            SELECTED=$(echo "$HOSTS" | cut -d',' -f2)
          else
            echo "Invalid TARGET_SERVER value: $TARGET"
            exit 1
          fi

          echo "SELECTED_HOSTS=$SELECTED" >> $GITHUB_OUTPUT

      # Deploy on selected servers
      - name: Deploy App on Selected EC2 Servers
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ steps.server_select.outputs.SELECTED_HOSTS }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo bash /opt/deploy/deploy_app.sh
