name: Deploy App

on:
  push:
    paths:
      - "app/**"
      - ".github/workflows/app-deploy.yml"

jobs:
  deploy-app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Login to GHCR
      - name: Login to GHCR
        run: |
          echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u vateam0864-glitch --password-stdin

      # Build App Image
      - name: Build App Image
        run: |
          docker build -t lnpr-app:latest ./app
          docker tag lnpr-app:latest ghcr.io/vateam0864-glitch/lnpr-cicd-template:latest

      # Push Image to GHCR
      - name: Push Image
        run: docker push ghcr.io/vateam0864-glitch/lnpr-cicd-template:latest


      # ------------------------------------------------------
      # SELECT SERVERS BASED ON COMMIT MESSAGE
      # ------------------------------------------------------
      - name: Select Target Servers (via commit message)
        id: server_select
        run: |
          HOSTS="${{ secrets.EC2_HOST }}"   # Ex: 51.20.251.59,13.48.105.140
          MSG="${{ github.event.head_commit.message }}"

          echo "Commit message: $MSG"

          if echo "$MSG" | grep -qi "server1"; then
            echo "Deploying to SERVER 1"
            SELECTED=$(echo "$HOSTS" | cut -d',' -f1)

          elif echo "$MSG" | grep -qi "server2"; then
            echo "Deploying to SERVER 2"
            SELECTED=$(echo "$HOSTS" | cut -d',' -f2)

          elif echo "$MSG" | grep -qi "all"; then
            echo "Deploying to ALL servers"
            SELECTED="$HOSTS"

          else
            echo "❌ ERROR: No valid server target found in commit message."
            echo "Add one of these keywords to your commit message:"
            echo "  (server1)  → deploy only to server 1"
            echo "  (server2)  → deploy only to server 2"
            echo "  (all)      → deploy to ALL servers"
            exit 1
          fi

          echo "Selected Hosts: $SELECTED"
          echo "SELECTED_HOSTS=$SELECTED" >> $GITHUB_OUTPUT


      # ------------------------------------------------------
      # DEPLOY APP ON ONE OR MULTIPLE SERVERS
      # ------------------------------------------------------
      - name: Deploy App on Selected EC2 Servers
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ steps.server_select.outputs.SELECTED_HOSTS }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Starting deployment..."
            sudo bash /opt/deploy/deploy_app.sh
