name: Deploy App

on:
  push:
    paths:
      - "app/**"
      - ".github/workflows/app-deploy.yml"

jobs:
  deploy-app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Login to GHCR
      - name: Login to GHCR
        run: |
          echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u vateam0864-glitch --password-stdin

      # Build App Image
      - name: Build app image
        run: |
          docker build -t lnpr-app:latest ./app
          docker tag lnpr-app:latest ghcr.io/vateam0864-glitch/lnpr-cicd-template:latest

      # Push Image
      - name: Push image to GHCR
        run: docker push ghcr.io/vateam0864-glitch/lnpr-cicd-template:latest

      # Deploy to EC2(s)
      - name: Deploy App on EC2 (multi-server)
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.TARGET_SERVER == 'all' && secrets.EC2_HOSTS || secrets.TARGET_SERVER }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo bash /opt/deploy/deploy_app.sh
