name: Deploy App

on:
  push:
    paths:
      - "app/**"
      - ".github/workflows/app-deploy.yml"

jobs:
  deploy-app:
    runs-on: ubuntu-latest

    # Make secrets available as env (avoids VS Code errors)
    env:
      TARGET_SERVER: ${{ secrets.TARGET_SERVER }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # ----------------------------
      # Login to GitHub Container Registry
      # ----------------------------
      - name: Login to GHCR
        run: |
          echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u vateam0864-glitch --password-stdin

      # ----------------------------
      # Build & Push Docker Image
      # ----------------------------
      - name: Build App Image
        run: |
          docker build -t lnpr-app:latest ./app
          docker tag lnpr-app:latest ghcr.io/vateam0864-glitch/lnpr-cicd-template:latest

      - name: Push Image to GHCR
        run: |
          docker push ghcr.io/vateam0864-glitch/lnpr-cicd-template:latest

      # ============================
      # Deploy to SERVER 1
      # ============================
      - name: Deploy to Server 1
        if: env.TARGET_SERVER == 'server1' || env.TARGET_SERVER == 'all'
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SERVER1_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY_SERVER1 }}
          script: |
            sudo bash /opt/deploy/deploy_app.sh

      # ============================
      # Deploy to SERVER 2
      # ============================
      - name: Deploy to Server 2
        if: env.TARGET_SERVER == 'server2' || env.TARGET_SERVER == 'all'
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SERVER2_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY_SERVER2 }}
          script: |
            sudo bash /opt/deploy/deploy_app.sh
