name: Deploy App

on:
  push:
    paths:
      - "app/**"
      - ".github/workflows/app-deploy.yml"

jobs:
  deploy-app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Login to GHCR
      - name: Login to GHCR
        run: |
          echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u vateam0864-glitch --password-stdin

      # Build App Image
      - name: Build app image
        run: |
          docker build -t lnpr-app:latest ./app
          docker tag lnpr-app:latest ghcr.io/vateam0864-glitch/lnpr-cicd-template:latest

      # Push Image
      - name: Push image to GHCR
        run: docker push ghcr.io/vateam0864-glitch/lnpr-cicd-template:latest

      # Decide target servers
      - name: Select Target Servers
        id: select
        run: |
          SERVER1="${{ secrets.SERVER1_IP }}"
          SERVER2="${{ secrets.SERVER2_IP }}"
          TARGET="${{ secrets.TARGET_SERVER }}"

          if [ "$TARGET" = "all" ]; then
            HOSTS="$SERVER1,$SERVER2"
          elif [ "$TARGET" = "server1" ]; then
            HOSTS="$SERVER1"
          elif [ "$TARGET" = "server2" ]; then
            HOSTS="$SERVER2"
          else
            echo "Invalid TARGET_SERVER value: $TARGET"
            exit 1
          fi

          echo "HOSTS=$HOSTS" >> $GITHUB_OUTPUT

      # Deploy
      - name: Deploy to Selected Servers
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ steps.select.outputs.HOSTS }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo bash /opt/deploy/deploy_app.sh
