name: Deploy App

on:
  push:
    paths:
      - "app/**"
      - ".github/workflows/app-deploy.yml"

jobs:
  deploy-app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Login to GHCR
      - name: Login to GHCR
        run: |
          echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u vateam0864-glitch --password-stdin

      # Build App Image
      - name: Build app image
        run: |
          docker build -t lnpr-app:latest ./app
          docker tag lnpr-app:latest ghcr.io/vateam0864-glitch/lnpr-cicd-template:latest

      # Push Image
      - name: Push image to GHCR
        run: docker push ghcr.io/vateam0864-glitch/lnpr-cicd-template:latest

      # Decide target servers
      - name: Select Target Servers
        id: select
        run: |
          if [ "${{ secrets.TARGET_SERVER }}" = "server1" ]; then
            echo "HOSTS=${{ secrets.SERVER1_IP }}" >> $GITHUB_OUTPUT
          elif [ "${{ secrets.TARGET_SERVER }}" = "server2" ]; then
            echo "HOSTS=${{ secrets.SERVER2_IP }}" >> $GITHUB_OUTPUT
          elif [ "${{ secrets.TARGET_SERVER }}" = "all" ]; then
            echo "HOSTS=${{ secrets.SERVER1_IP }},${{ secrets.SERVER2_IP }}" >> $GITHUB_OUTPUT
          else
            echo "Invalid TARGET_SERVER value"
            exit 1
          fi

      # Deploy
      - name: Deploy to Selected Servers
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ steps.select.outputs.HOSTS }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo bash /opt/deploy/deploy_app.sh
