name: Deploy App

on:
  push:
    branches:
      - main              # ðŸš€ Trigger ONLY on main branch
    paths:
      - "app/**"          # Only when application code changes
      - ".github/workflows/app-deploy.yml"

jobs:
  deploy-app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Login to GHCR
      - name: Login to GHCR
        run: |
          echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u vateam0864-glitch --password-stdin

      # Build and Tag Docker Image
      - name: Build app image
        run: |
          docker build -t lnpr-app:latest ./app
          docker tag lnpr-app:latest ghcr.io/vateam0864-glitch/lnpr-cicd-template:latest

      # Push Image to GHCR
      - name: Push image to GHCR
        run: docker push ghcr.io/vateam0864-glitch/lnpr-cicd-template:latest

      # Deploy on EC2
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo bash /opt/deploy/deploy_app.sh
