name: Deploy CV Package

on:
  push:
    branches:
      - main                # ðŸš€ Trigger ONLY on main branch
    paths:
      - "cv_package/**"      # Only run when package files change
      - ".github/workflows/package-deploy.yml"

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Build the CV Package
      - name: Build CV Package
        run: |
          chmod +x cv_package/build_package.sh
          ./cv_package/build_package.sh
          ls -l

      # Upload TAR file to EC2
      - name: Upload CV Package to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "cvpack_v1.tar.gz"
          target: "/opt/lnpr/"
