name: Deploy CV Package

on:
  push:
    paths:
      - "cv_package/**"
      - ".github/workflows/package-deploy.yml"

jobs:
  deploy-package:
    runs-on: ubuntu-latest

    env:
      TARGET_SERVER: ${{ secrets.TARGET_SERVER }}

    steps:
      - uses: actions/checkout@v3

      - name: Build CV Package
        run: |
          chmod +x cv_package/build_package.sh
          ./cv_package/build_package.sh
          ls -lh cvpack_v1.tar.gz

      # ---------------- SERVER 2 ----------------
      - name: Upload CV Package to Server 2
        if: env.TARGET_SERVER == 'server2' || env.TARGET_SERVER == 'all'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER2_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY_SERVER2 }}
          source: "cvpack_v1.tar.gz"
          target: "/opt/lnpr/"
          overwrite: true

      - name: Apply CV Package on Server 2
        if: env.TARGET_SERVER == 'server2' || env.TARGET_SERVER == 'all'
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SERVER2_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY_SERVER2 }}
          script: |
            sudo bash /opt/deploy/deploy_package.sh
