name: Deploy CV Package

on:
  push:
    paths:
      - "cv_package/**"
      - ".github/workflows/package-deploy.yml"

jobs:
  deploy-package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Build package (tar)
      - name: Build CV Package
        run: |
          chmod +x cv_package/build_package.sh
          ./cv_package/build_package.sh
          ls -l

      # Upload package to server(s)
      - name: Upload CV Package (multi-server)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.TARGET_SERVER == 'all' && secrets.EC2_HOSTS || secrets.TARGET_SERVER }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "cvpack_v1.tar.gz"
          target: "/opt/lnpr/"

      # Run deploy_package.sh on servers
      - name: Apply CV Package on EC2
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.TARGET_SERVER == 'all' && secrets.EC2_HOSTS || secrets.TARGET_SERVER }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo bash /opt/deploy/deploy_package.sh
