name: Deploy CV Package

on:
  push:
    paths:
      - "cv_package/**"
      - ".github/workflows/package-deploy.yml"

jobs:
  deploy-package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Build package (tar)
      - name: Build CV Package
        run: |
          chmod +x cv_package/build_package.sh
          ./cv_package/build_package.sh
          ls -l

      # Decide target servers
      - name: Select Target Servers
        id: select
        run: |
          SERVER1="${{ secrets.SERVER1_IP }}"
          SERVER2="${{ secrets.SERVER2_IP }}"
          TARGET="${{ secrets.TARGET_SERVER }}"

          if [ "$TARGET" = "all" ]; then
            HOSTS="$SERVER1,$SERVER2"
          elif [ "$TARGET" = "server1" ]; then
            HOSTS="$SERVER1"
          elif [ "$TARGET" = "server2" ]; then
            HOSTS="$SERVER2"
          else
            echo "Invalid TARGET_SERVER value: $TARGET"
            exit 1
          fi

          echo "HOSTS=$HOSTS" >> $GITHUB_OUTPUT

      # Upload package tar to selected servers
      - name: Upload CV Package
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ steps.select.outputs.HOSTS }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "cvpack_v1.tar.gz"
          target: "/opt/lnpr/"

      # Run deploy script
      - name: Apply CV Package on EC2
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ steps.select.outputs.HOSTS }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo bash /opt/deploy/deploy_package.sh
